# Generated by Django 5.2.5 on 2026-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('farm', 'Farm'), ('cow-products', 'Cow Products'), ('agriculture', 'Agriculture')], max_length=20),
        ),
    ]
